### ISSUE TITLE
Update this document to use Metanorma instead of the old asciidoctor-rfc

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/rfc-asciidoc-rfc#26]
The old asciidoctor rfc is documented as v2 metanorma-ietf on metanorma.com

**Comment by ronaldtse** [comment]
@metanorma/editors can you help convert this document? Thanks!

**Comment by manuelfuenmayor** [comment]
@ronaldtse, excuse me, I don't understand. Which document should we convert?
In reference-docs folder there are: rfc7328.txt, rfc5385.txt, and draft-gieben-mmark2rfc-00.txt. Some of these?

**Comment by ronaldtse** [comment]
Convert the core document in this repo inside `sources`. I think the current doc doesn't compile properly in MN...

**Comment by CAMOBAP** [comment]
@ronaldtse probably this one can be closed

**Comment by ronaldtse** [comment]
Apparently @manuel489 reported that this document is not working, we have to fix it.

**Comment by manuelfuenmayor** [comment]
According to @CAMOBAP, there is a bug left to address: https://github.com/metanorma/rfc-asciidoc-rfc/issues/32

**Comment by ronaldtse** [comment]
From https://github.com/metanorma/metanorma/issues/295 : this task is now urgent. @manuelfuenmayor @anermina please help. Thanks!

**Comment by cisba** [comment]
Output compiling with windows (choco) package:

```
$ metanorma compile -x html,txt draft-ribose-asciirfc.adoc
Traceback (most recent call last):
        27: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/src/metanorma:
217:in `<main>'
        26: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli.rb:34:in `start'
        25: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        24: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        23: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        22: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        21: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        20: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli/command.rb:48:in `compile'
        19: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli/command.rb:48:in `each'
        18: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli/command.rb:48:in `block in comp
ile'
        17: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli/command.rb:244:in `compile_docu
ment'
        16: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli/compiler.rb:35:in `compile'
        15: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli/compiler.rb:30:in `compile'
        14: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli/compiler.rb:45:in `compile_file
'
        13: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:33:in `compile'
        12: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:42:in `process_input'
        11: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:60:in `process_input_adoc'
        10: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-1.5.10/lib/metanorma/processor.rb:21:in `input_to_isodoc'
         9: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-1.5.10/lib/metanorma/input/asciidoc.rb:13:in `process'
         8: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-1.5.10/lib/metanorma/input/asciidoc.rb:25:in `asciidoctor_v
alidate'
         7: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/asciidoctor-2.0.20/lib/asciidoctor/load.rb:84:in `load'
         6: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:532:in `parse'
         5: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:532:in `each'
         4: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:533:in `block in parse
'
         3: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:533:in `[]'
         2: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-plugin-glossarist-0.1.2/lib/metanorma/plugin/glossarist/dat
aset_preprocessor.rb:78:in `process'
         1: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-plugin-glossarist-0.1.2/lib/metanorma/plugin/glossarist/doc
ument.rb:23:in `to_s'
C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/2.7.0/gems/metano
rma-plugin-glossarist-0.1.2/lib/metanorma/plugin/glossarist/document.rb:23:in `j
oin': incompatible character encodings: UTF-8 and CP850 (Encoding::Compatibility
Error)
        27: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/src/metanorma:
217:in `<main>'
        26: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli.rb:34:in `start'
        25: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        24: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        23: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        22: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        21: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        20: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli/command.rb:48:in `compile'
        19: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli/command.rb:48:in `each'
        18: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli/command.rb:48:in `block in comp
ile'
        17: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli/command.rb:244:in `compile_docu
ment'
        16: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli/compiler.rb:35:in `compile'
        15: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli/compiler.rb:30:in `compile'
        14: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-cli-1.7.3/lib/metanorma/cli/compiler.rb:45:in `compile_file
'
        13: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:33:in `compile'
        12: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:42:in `process_input'
        11: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:60:in `process_input_adoc'
        10: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-1.5.10/lib/metanorma/processor.rb:21:in `input_to_isodoc'
         9: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-1.5.10/lib/metanorma/input/asciidoc.rb:13:in `process'
         8: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-1.5.10/lib/metanorma/input/asciidoc.rb:25:in `asciidoctor_v
alidate'
         7: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/asciidoctor-2.0.20/lib/asciidoctor/load.rb:84:in `load'
         6: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:532:in `parse'
         5: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:532:in `each'
         4: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:533:in `block in parse
'
         3: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:533:in `[]'
         2: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-plugin-glossarist-0.1.2/lib/metanorma/plugin/glossarist/dat
aset_preprocessor.rb:78:in `process'
         1: from C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/
2.7.0/gems/metanorma-plugin-glossarist-0.1.2/lib/metanorma/plugin/glossarist/doc
ument.rb:23:in `to_s'
C:/Users/ecisbani/AppData/Local/Temp/ocr2C68.tmp/lib/ruby/gems/2.7.0/gems/metano
rma-plugin-glossarist-0.1.2/lib/metanorma/plugin/glossarist/document.rb:23:in `j
oin': asciidoctor: FAILED: draft-ribose-asciirfc.adoc: Failed to load AsciiDoc d
ocument - incompatible character encodings: UTF-8 and CP850 (Encoding::Compatibi
lityError)
```

**Comment by manuelfuenmayor** [comment]
This task is solved now. For reference, see https://github.com/metanorma/metanorma/issues/295 and https://github.com/cisba/i-d_dlts/pull/1.

**Comment by cisba** [comment]
Hi people, today I uploaded to IETF the draft https://github.com/cisba/i-d_dlts and got the error "The Abstract section seems to be numbered" (see original long output below).

This error seems related to the new template used by Metanorma and it is really a big issue because it is blocking the submission process to IETF.

@ronaldtse @manuelfuenmayor 

`Submission rejected: Checks failed: idnits 2.17.00 (12 Aug 2021) /a/www/www6s/staging/draft-intesigroup-dlts-08.txt: ** The Abstract section seems to be numbered Showing Errors (**), Flaws (~~), Warnings (==), and Comments (--). Errors MUST be fixed before draft submission. Flaws SHOULD be fixed before draft submission. Checking boilerplate required by [RFC 5378](https://datatracker.ietf.org/doc/rfc5378/) and the IETF Trust (see https://trustee.ietf.org/license-info): ---------------------------------------------------------------------------- No issues found here. Checking nits according to https://www.ietf.org/id-info/1id-guidelines.txt: ---------------------------------------------------------------------------- No issues found here. Running in submission checking mode -- *not* checking nits according to https://www.ietf.org/id-info/checklist . ---------------------------------------------------------------------------- Summary: 1 error (**), 0 flaws (~~), 0 warnings (==), 0 comments (--).`

**Comment by opoudjis** [comment]
Lodged in https://github.com/metanorma/metanorma-ietf/issues/210

**Comment by manuelfuenmayor** [comment]
@ronaldtse, @opoudjis  the "Normative references" section in this document has this content:

```adoc
[bibliography]
== Normative References

//bibliography::norm[]
++++
include::../references/normative/*.xml[]
++++

[bibliography]
== Informative References

//bibliography::info[]
++++
include::../references/informative/*.xml[]
++++
```

This is meant to take the references from the XML files located at `references/`. But this doesn't work.

Do we need to convert these references to the typical bibliographic markup?
That is: `* [[[anchor, id]]], text...`

**Comment by opoudjis** [comment]
https://www.metanorma.org/author/topics/blocks/passthroughs/#passthrough-blocks

You need to tell it that the XML you are importing is specific to the RFC XML format:

````
[format=rfc]
++++
include::../references/normative/*.xml[]
++++
````

I can't get the document compiling locally because of all the broken xrefs.

**Comment by ronaldtse** [comment]
@manuelfuenmayor please try to update them into the typical markup. For the ones that cannot be auto fetched, use bibliographic spans. Thanks!

**Comment by manuelfuenmayor** [comment]
> ... please try to update them into the typical markup.

@ronaldtse, are you sure? Because I've confirmed that these references render correctly by using the `[format=rfc]` attribute (thanks to Nick's intervention). It is just necessary to address some bugs that I've already reported.

**Comment by ronaldtse** [comment]
> > ... please try to update them into the typical markup.
> 
> @ronaldtse, are you sure? Because I've confirmed that these references render correctly by using the `[format=rfc]` attribute (thanks to Nick's intervention). It is just necessary to address some bugs that I've already reported.

Yes there is no need to keep RFC XML lying around. Furthermore, do realize that this document cannot be published in any other format (except `rfc`) when those XML files are used.
